stages:
  - deploy

variables:
  DOCKER_DRIVER: overlay2

deploy:
  stage: deploy
  image: docker:24.0.5
  services:
  - docker:24.0.5-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'